apiVersion: v1 
kind: Pod 
metadata:
  name: node-selector
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes: 
  - name: persistent-storage 
    persistentVolumeClaim: 
      claimName: ebs-static